package com.cureone.pharmacyandinventory.service;

import com.cureone.common.DBUtil;
import com.cureone.pharmacyandinventory.model.PrescriptionItem;

import java.sql.*;
import java.util.List;
import java.util.Map;

public class PrescriptionService {

    /**
     * Creates a prescription and reduces stock atomically.
     * @param appointmentId appointment id or null
     * @param doctorId doctor id
     * @param patientId patient id
     * @param items map of medicineId -> qty
     * @return prescription id or -1 on fail
     */
    public int createPrescription(Integer appointmentId, Integer doctorId, Integer patientId, List<PrescriptionItem> items) {
        String insertPres = "INSERT INTO prescriptions (appointment_id, doctor_id, patient_id, notes) VALUES (?, ?, ?, ?)";
        String insertItem = "INSERT INTO prescription_items (prescription_id, medicine_id, quantity, unit_price) VALUES (?, ?, ?, ?)";
        String selectStock = "SELECT quantity FROM stock WHERE medicine_id = ? FOR UPDATE";
        String updateStock = "UPDATE stock SET quantity = quantity - ? WHERE medicine_id = ?";
        String selectPrice = "SELECT price FROM medicines WHERE id = ?";

        Connection c = null;
        try {
            c = DBUtil.getConnection();
            c.setAutoCommit(false);

            // 1) Insert prescription
            int presId;
            try (PreparedStatement ps = c.prepareStatement(insertPres, Statement.RETURN_GENERATED_KEYS)) {
                if (appointmentId == null) ps.setNull(1, Types.INTEGER); else ps.setInt(1, appointmentId);
                if (doctorId == null) ps.setNull(2, Types.INTEGER); else ps.setInt(2, doctorId);
                if (patientId == null) ps.setNull(3, Types.INTEGER); else ps.setInt(3, patientId);
                ps.setString(4, "Generated by PrescriptionService");
                ps.executeUpdate();
                try (ResultSet rs = ps.getGeneratedKeys()) {
                    if (rs.next()) presId = rs.getInt(1);
                    else throw new SQLException("Failed to get prescription id");
                }
            }

            // 2) For each item: check stock and decrement
            for (PrescriptionItem it : items) {
                int medId = it.getMedicineId();
                int qty = it.getQuantity();

                // lock row
                try (PreparedStatement psSel = c.prepareStatement(selectStock)) {
                    psSel.setInt(1, medId);
                    try (ResultSet rs = psSel.executeQuery()) {
                        if (!rs.next()) throw new SQLException("No stock row for medicine " + medId);
                        int avail = rs.getInt("quantity");
                        if (avail < qty) throw new SQLException("Insufficient stock for medicine " + medId + " (available=" + avail + ", requested=" + qty +")");
                    }
                }

                // decrement
                try (PreparedStatement psUpd = c.prepareStatement(updateStock)) {
                    psUpd.setInt(1, qty);
                    psUpd.setInt(2, medId);
                    psUpd.executeUpdate();
                }

                // get unit price (simple)
                double unitPrice = 0.0;
                try (PreparedStatement psPrice = c.prepareStatement(selectPrice)) {
                    psPrice.setInt(1, medId);
                    try (ResultSet rs = psPrice.executeQuery()) {
                        if (rs.next()) unitPrice = rs.getDouble("price");
                    }
                }

                // insert prescription item
                try (PreparedStatement psIns = c.prepareStatement(insertItem)) {
                    psIns.setInt(1, presId);
                    psIns.setInt(2, medId);
                    psIns.setInt(3, qty);
                    psIns.setDouble(4, unitPrice);
                    psIns.executeUpdate();
                }
            }

            c.commit();
            return presId;

        } catch (Exception ex) {
            try { if (c != null) c.rollback(); } catch (Exception e) { e.printStackTrace(); }
            System.err.println("Prescription failed: " + ex.getMessage());
            ex.printStackTrace();
            return -1;
        } finally {
            try { if (c != null) { c.setAutoCommit(true); c.close(); } } catch (Exception e) { e.printStackTrace(); }
        }
    }
}
